import toHash from 'tohash'
import { getAssetUrl } from '../../../shared/assets'

export const FONTS = [
  {
    id: 'Google Sans Code',
    name: 'Google Sans Code',
    assetUrl:
      'https://cdn.jsdelivr.net/fontsource/fonts/google-sans-code@latest/latin-400-normal.woff',
    assetFormat: 'woff',
  },
  {
    id: 'HarmonyOS Sans',
    name: 'HarmonyOS Sans',
    assetUrl:
      'https://cdn.jsdelivr.net/gh/ajacocks/harmonyos-sans-font@main/HarmonyOS_Sans/HarmonyOS_Sans_Regular.ttf',
    assetFormat: 'truetype',
  },
  {
    id: 'Cascadia Code',
    name: 'Cascadia Code',
    assetUrl:
      'https://cdn.jsdelivr.net/fontsource/fonts/cascadia-code@latest/latin-400-normal.woff',
    assetFormat: 'woff',
  },
  {
    id: 'Hack',
    name: 'Hack',
    assetUrl: 'https://cdnjs.cloudflare.com/ajax/libs/hack-font/3.3.0/web/fonts/hack-regular.woff',
    assetFormat: 'woff',
  },
  {
    id: 'Anonymous Pro',
    name: 'Anonymous Pro',
    assetUrl:
      'https://cdn.jsdelivr.net/fontsource/fonts/anonymous-pro@latest/latin-400-normal.woff',
    assetFormat: 'woff',
  },
  {
    id: 'Droid Sans Mono',
    name: 'Droid Sans Mono',
    assetUrl:
      'https://android.googlesource.com/platform/frameworks/base/+/master/data/fonts/DroidSansMono.ttf?format=TEXT',
    assetFormat: 'truetype',
    assetEncoding: 'base64-text',
  },
  {
    id: 'Fantasque Sans Mono',
    name: 'Fantasque Sans Mono',
    assetUrl:
      'https://cdn.jsdelivr.net/npm/@typopro/web-fantasque-sans-mono@3.7.5/TypoPRO-FantasqueSansMono-Regular.woff',
    assetFormat: 'woff',
  },
  {
    id: 'Fira Code',
    name: 'Fira Code',
    assetUrl: 'https://cdn.jsdelivr.net/npm/firacode@latest/distr/woff/FiraCode-Regular.woff',
    assetFormat: 'woff',
  },
  {
    id: 'IBM Plex Mono',
    name: 'IBM Plex Mono',
    assetUrl:
      'https://cdn.jsdelivr.net/fontsource/fonts/ibm-plex-mono@latest/latin-400-normal.woff',
    assetFormat: 'woff',
  },
  {
    id: 'Inconsolata',
    name: 'Inconsolata',
    assetUrl: 'https://cdn.jsdelivr.net/fontsource/fonts/inconsolata@latest/latin-400-normal.woff',
    assetFormat: 'woff',
  },
  {
    id: 'JetBrains Mono',
    name: 'JetBrains Mono',
    assetUrl:
      'https://cdn.jsdelivr.net/fontsource/fonts/jetbrains-mono@latest/latin-400-normal.woff',
    assetFormat: 'woff',
  },
  {
    id: 'Monoid',
    name: 'Monoid',
    assetUrl: 'https://cdn.jsdelivr.net/npm/@typopro/web-monoid@3.7.5/TypoPRO-Monoid-Regular.woff',
    assetFormat: 'woff',
  },
  {
    id: 'Source Code Pro',
    name: 'Source Code Pro',
    assetUrl:
      'https://cdn.jsdelivr.net/fontsource/fonts/source-code-pro@latest/latin-400-normal.woff',
    assetFormat: 'woff',
  },
  {
    id: 'Space Mono',
    name: 'Space Mono',
    assetUrl: 'https://cdn.jsdelivr.net/fontsource/fonts/space-mono@latest/latin-400-normal.woff',
    assetFormat: 'woff',
  },
  {
    id: 'Ubuntu Mono',
    name: 'Ubuntu Mono',
    assetUrl: 'https://cdn.jsdelivr.net/fontsource/fonts/ubuntu-mono@latest/latin-400-normal.woff',
    assetFormat: 'woff',
  },
]

export const HIGHLIGHT_KEYS = [
  'background',
  'text',
  'variable',
  'attribute',
  'definition',
  'keyword',
  'operator',
  'property',
  'number',
  'string',
  'comment',
  'meta',
]

export const THEMES = [
  {
    id: 'panda-syntax',
    name: 'Panda',
    highlights: {
      background: '#292A2B',
      text: '#E6E6E6',
      variable: '#ffb86c',
      variable2: '#ff9ac1',
      variable3: '#ff9ac1',
      attribute: '#ffb86c',
      definition: '#e6e6e6',
      keyword: '#FF75B5',
      operator: '#f3f3f3',
      property: '#f3f3f3',
      number: '#FFB86C',
      string: '#19F9D8',
      comment: '#676B79',
      meta: '#b084eb',
      tag: '#ff2c6d',
    },
  },
  {
    id: 'panda-Gradation',
    name: 'Panda（Gradation）',
    highlights: {
      background: 'rgba(0,0,0,.25)',
      text: '#E6E6E6',
      variable: '#ffb86c',
      variable2: '#ff9ac1',
      variable3: '#ff9ac1',
      attribute: '#ffb86c',
      definition: '#e6e6e6',
      keyword: '#FF75B5',
      operator: '#f3f3f3',
      property: '#f3f3f3',
      number: '#FFB86C',
      string: '#19F9D8',
      comment: '#676B79',
      meta: '#b084eb',
      tag: '#ff2c6d',
    },
  },
  {
    id: 'Panda-Gradation',
    name: 'Panda Light(Gradation)',
    light: true,
    highlights: {
      background: 'rgba(255,255,255,.25)',
      text: '#333',
      variable: '#e06c75',
      variable2: '#e45649',
      attribute: '#d19a66',
      definition: '#4078f2',
      keyword: '#a626a4',
      operator: '#0184bc',
      property: '#4078f2',
      number: '#986801',
      string: '#50a14f',
      comment: '#a0a1a7',
      meta: '#383a42',
      tag: '#e45649',
    },
  },
  {
    id: 'vscode',
    name: 'VSCode',
    highlights: {
      background: '#1E1E1E',
      text: '#D4D4D4',
      variable: '#9CDCFE',
      attribute: '#d19a66',
      definition: '#DCDCAA',
      keyword: '#C586C0',
      operator: '#D4D4D4',
      property: '#DCDCAA',
      number: '#B5CEA8',
      string: '#CE9178',
      comment: '#6A9955',
      meta: '#D4D4D4',
      tag: '#569cd6',
    },
  },
  {
    id: 'vscode-Gradation',
    name: 'VSCode（Gradation）',
    highlights: {
      background: 'rgba(0,0,0,.15)',
      text: '#D4D4D4',
      variable: '#9CDCFE',
      attribute: '#d19a66',
      definition: '#DCDCAA',
      keyword: '#C586C0',
      operator: '#D4D4D4',
      property: '#DCDCAA',
      number: '#B5CEA8',
      string: '#CE9178',
      comment: '#6A9955',
      meta: '#D4D4D4',
      tag: '#569cd6',
    },
  },

  {
    id: 'verminal',
    name: 'Verminal',
    highlights: {
      background: 'rgba(0, 0, 0, 0.85)',
      text: '#fff',
      variable: '#ff9ba3',
      variable2: '#fff',
      attribute: '#d19a66',
      definition: '#34B7FF',
      keyword: '#9AE1FF',
      operator: '#FA78C3',
      property: '#0af',
      number: '#d19a66',
      string: '#98c379',
      comment: '#5c6370',
      meta: '#abb2bf',
      tag: '#e06c75',
    },
  },
  {
    id: '3024-night',
    name: '3024 Night',
    highlights: {
      background: '#090300',
      text: '#d6d5d4',
      variable: '#01a252',
      variable2: '#01a0e4',
      attribute: '#00c',
      definition: '#e8bbd0',
      keyword: '#db2d20',
      operator: '#fff',
      property: '#01a252',
      number: '#a16a94',
      string: '#fded02',
      comment: '#cdab53',
      meta: '#555',
    },
  },
  {
    id: 'a11y-dark',
    name: 'A11y Dark',
    highlights: {
      background: '#2b2b2b',
      text: '#f8f8f2',
      variable: '#00e0e0',
      attribute: '#abe338',
      definition: '#ffd700',
      keyword: '#ffa07a',
      operator: '#f8f8f2',
      property: '#abe338',
      number: '#dcc6e0',
      string: '#ffd700',
      comment: '#d4d0ab',
      meta: '#d4d0ab',
      tag: '#dcc6e0',
    },
  },
  {
    id: 'blackboard',
    name: 'Blackboard',
    highlights: {
      background: '#0C1021',
      text: '#F8F8F8',
      variable: '#FF6400',
      attribute: '#8DA6CE',
      definition: '#8DA6CE',
      keyword: '#FBDE2D',
      operator: '#fff',
      property: '#fff',
      number: '#D8FA3C',
      string: '#61CE3C',
      comment: '#AEAEAE',
      meta: '#D8FA3C',
      tag: '#8DA6CE',
    },
  },
  {
    id: 'one-light',
    name: 'One Light',
    light: true,
    highlights: {
      background: '#fafafa',
      text: '#383a42',
      variable: '#e06c75',
      variable2: '#e45649',
      attribute: '#d19a66',
      definition: '#4078f2',
      keyword: '#a626a4',
      operator: '#0184bc',
      property: '#4078f2',
      number: '#986801',
      string: '#50a14f',
      comment: '#a0a1a7',
      meta: '#383a42',
      tag: '#e45649',
    },
  },
  {
    id: 'one-dark',
    name: 'One Dark',
    highlights: {
      background: '#282c34',
      text: '#abb2bf',
      variable: '#e06c75',
      attribute: '#d19a66',
      definition: '#e5c07b',
      keyword: '#c678dd',
      operator: '#56b6c2',
      property: '#56b6c2',
      number: '#d19a66',
      string: '#98c379',
      comment: '#5c6370',
      meta: '#abb2bf',
      tag: '#e06c75',
    },
  },

  {
    id: 'base16-light',
    name: 'Base 16 (Light)',
    light: true,
    highlights: {
      background: '#f5f5f5',
      text: '#202020',
      variable: '#90a959',
      variable2: '#6a9fb5',
      attribute: '#90a959',
      definition: '#d28445',
      keyword: '#ac4142',
      operator: '#000',
      property: '#90a959',
      number: '#aa759f',
      string: '#f4bf75',
      comment: '#8f5536',
      meta: '#555',
      tag: '#ac4142',
    },
  },
  {
    id: 'base16-dark',
    name: 'Base 16 (Dark)',
    highlights: {
      background: '#151515',
      text: '#e0e0e0',
      variable: '#90a959',
      variable2: '#6a9fb5',
      attribute: '#00c',
      definition: '#d28445',
      keyword: '#ac4142',
      operator: '#fff',
      property: '#90a959',
      number: '#aa759f',
      string: '#f4bf75',
      comment: '#8f5536',
      meta: '#555',
      tag: '#ac4142',
    },
  },
  {
    id: 'cobalt',
    name: 'Cobalt',
    highlights: {
      background: '#002240',
      text: '#fff',
      variable: '#9effff',
      variable3: 'white',
      attribute: '#ff80e1',
      definition: '#fff',
      keyword: '#ffee80',
      operator: '#fff',
      property: '#fff',
      number: '#ff80e1',
      string: '#3ad900',
      comment: '#08f',
      meta: '#ff9d00',
      tag: '#9effff',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    highlights: {
      background: '#22212C',
      text: '#F8F8F2',
      variable: '#8AFF80',
      variable2: '#8AFF80',
      variable3: '#F8F8F2',
      attribute: '#8AFF80',
      definition: '#8AFF80',
      keyword: '#FF80BF',
      operator: '#FF80BF',
      property: '#80FFEA',
      number: '#9580FF',
      string: '#FFFF80',
      comment: '#504C67',
      meta: '#F8F8F2',
      tag: '#FF80BF',
      builtin: '#80FFEA',
    },
  },
  {
    id: 'duotone-dark',
    name: 'Duotone',
    highlights: {
      background: '#2a2734',
      text: '#6c6783',
      variable: '#ffcc99',
      variable2: '#7a63ee',
      variable3: '#7a63ee',
      attribute: '#ffcc99',
      definition: '#eeebff',
      keyword: '#ffcc99',
      operator: '#ffad5c',
      property: '#9a86fd',
      number: '#ffcc99',
      string: '#ffb870',
      comment: '#6c6783',
      meta: '#555',
      tag: '#eeebff',
    },
  },
  {
    id: 'hopscotch',
    name: 'Hopscotch',
    highlights: {
      background: '#322931',
      text: '#d5d3d5',
      variable: '#8fc13e',
      variable2: '#1290bf',
      attribute: '#8fc13e',
      definition: '#fd8b19',
      keyword: '#dd464c',
      operator: '#fff',
      property: '#8fc13e',
      number: '#c85e7c',
      string: '#fdcc59',
      comment: '#b33508',
      meta: '#555',
      tag: '#dd464c',
    },
  },
  {
    id: 'lucario',
    name: 'Lucario',
    highlights: {
      background: '#2b3e50',
      text: '#f8f8f2',
      variable: '#f8f8f2',
      variable3: '#ffb86c',
      attribute: '#66D9EF',
      definition: '#72C05D',
      keyword: '#ff6541',
      operator: '#66D9EF',
      property: '#f8f8f2',
      number: '#ca94ff',
      string: '#E6DB74',
      comment: '#5c98cd',
      meta: '#f8f8f2',
      tag: '#ff6541',
    },
  },
  {
    id: 'material',
    name: 'Material',
    highlights: {
      background: '#263238',
      text: 'rgba(233, 237, 237, 1)',
      variable: '#82B1FF',
      variable2: '#80CBC4',
      variable3: '#DECB6B',
      attribute: '#FFCB6B',
      definition: 'rgba(233, 237, 237, 1)',
      keyword: 'rgba(199, 146, 234, 1)',
      operator: 'rgba(233, 237, 237, 1)',
      property: '#80CBAE',
      number: '#F77669',
      string: '#C3E88D',
      comment: '#546E7A',
      meta: '#80CBC4',
      tag: 'rgba(255, 83, 112, 1)',
    },
  },
  {
    id: 'monokai',
    name: 'Monokai',
    highlights: {
      background: '#272822',
      text: '#f8f8f2',
      variable: '#f8f8f2',
      variable2: '#9effff',
      variable3: '#66d9ef',
      attribute: '#a6e22e',
      definition: '#fd971f',
      keyword: '#f92672',
      operator: '#fff',
      property: '#a6e22e',
      number: '#ae81ff',
      string: '#e6db74',
      comment: '#75715e',
      meta: '#555',
      tag: '#bc6283',
    },
  },
  {
    id: 'night-owl',
    name: 'Night Owl',
    highlights: {
      background: '#011627',
      text: '#abb2bf',
      variable: '#82AAFF',
      attribute: '#F78C6C',
      definition: '#82AAFF',
      keyword: '#c792ea',
      operator: '#c792ea',
      property: '#fff',
      number: '#F78C6C',
      string: '#ecc48d',
      comment: '#5c6370',
      meta: '#7fdbca',
      tag: '#7fdbca',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    highlights: {
      background: '#2e3440',
      text: '#d8dee9',
      variable: '#88C0D0',
      variable3: '#d8dee9',
      attribute: '#8FBCBB',
      definition: '#D8DEE9',
      keyword: '#81A1C1',
      operator: '#81A1C1',
      property: '#D8DEE9',
      number: '#B48EAD',
      string: '#A3BE8C',
      comment: '#4C566A',
      meta: '#81A1C1',
      tag: '#81A1C1',
    },
  },
  {
    id: 'oceanic-next',
    name: 'Oceanic Next',
    highlights: {
      background: '#304148',
      text: '#f8f8f2',
      variable: '#f8f8f2',
      attribute: '#C594C5',
      definition: '#6699CC',
      keyword: '#C594C5',
      operator: '#fff',
      property: '#99C794',
      number: '#F99157',
      string: '#99C794',
      comment: '#65737E',
      meta: '#555',
      tag: '#C594C5',
    },
  },

  {
    id: 'paraiso-dark',
    name: 'Paraiso',
    highlights: {
      background: '#2f1e2e',
      text: '#b9b6b0',
      variable: '#48b685',
      variable2: '#06b6ef',
      attribute: '#48b685',
      definition: '#f99b15',
      keyword: '#ef6155;',
      operator: '#fff',
      property: '#48b685',
      number: '#815ba4',
      string: '#fec418',
      comment: '#e96ba8',
      meta: '#555',
      tag: '#ef6155',
    },
  },
  {
    id: 'seti',
    name: 'Seti',
    highlights: {
      background: '#151718',
      text: '#CFD2D1',
      variable: '#55b5db',
      variable2: '#a074c4',
      variable3: '#9fca56',
      attribute: '#9fca56',
      definition: '#55b5db',
      keyword: '#e6cd69',
      operator: '#9fca56',
      property: '#a074c4',
      number: '#cd3f45',
      string: '#55b5db',
      comment: '#41535b',
      meta: '#55b5db',
      tag: '#55b5db',
    },
  },
  {
    id: 'shades-of-purple',
    name: 'Shades of Purple ',
    highlights: {
      background: '#2D2B55',
      text: '#FFFFFF',
      variable: '#9EFFFF',
      attribute: '#9EFFFF',
      definition: '#9EFFFF',
      keyword: '#FF9D00',
      operator: '#FF9D00',
      property: '#FAD000',
      number: '#FF628C',
      string: '#A5FF90',
      comment: '#B362FF',
      meta: '#FF9D00',
      tag: '#9EFFFF',
    },
  },
  {
    id: 'slate-dark',
    name: 'Slate (Dark)',
    highlights: {
      background: '#161B22',
      text: '#D7DEE7',
      variable: '#A7B7C8',
      variable2: '#B8C6D5',
      variable3: '#D7DEE7',
      attribute: '#92A7BC',
      definition: '#C7D3DF',
      keyword: '#8EA9C2',
      operator: '#C8D3DF',
      property: '#B7C6D8',
      number: '#C6A374',
      string: '#90AB9B',
      comment: '#667383',
      meta: '#8190A2',
      tag: '#9CB0C5',
      builtin: '#9CB0C5',
    },
  },
  {
    id: 'slate-light',
    name: 'Slate (Light)',
    light: true,
    highlights: {
      background: '#F6F8FB',
      text: '#243142',
      variable: '#56718A',
      variable2: '#68839B',
      variable3: '#243142',
      attribute: '#5F7C96',
      definition: '#31475E',
      keyword: '#5E7B95',
      operator: '#5C6F82',
      property: '#42617B',
      number: '#A27A48',
      string: '#5E826F',
      comment: '#97A2B2',
      meta: '#6E8093',
      tag: '#587590',
      builtin: '#587590',
    },
  },
  {
    id: 'solarized dark',
    name: 'Solarized (Dark)',
    link: 'solarized',
    highlights: {
      background: '#002b36',
      text: '#839496',
      variable: '#839496',
      variable2: '#b58900',
      variable3: '#6c71c4',
      attribute: '#2aa198',
      definition: '#2aa198',
      keyword: '#cb4b16',
      operator: '#6c71c4',
      property: '#2aa198',
      number: '#d33682',
      string: '#859900',
      comment: '#586e75',
      meta: '#859900',
      tag: '#93a1a1',
    },
  },
  {
    id: 'solarized light',
    name: 'Solarized (Light)',
    link: 'solarized',
    light: true,
    highlights: {
      background: '#fdf6e3',
      text: '#657b83',
      variable: '#839496',
      variable2: '#b58900',
      variable3: '#6c71c4',
      attribute: '#2aa198',
      definition: '#2aa198',
      keyword: '#cb4b16',
      operator: '#6c71c4',
      property: '#2aa198',
      number: '#d33682',
      string: '#859900',
      comment: '#586e75',
      meta: '#859900',
      tag: '#93a1a1',
    },
  },
  {
    id: 'synthwave-84',
    name: "SynthWave '84",
    highlights: {
      background: '#2b213a',
      text: '#b6b1b1',
      variable: '#f92aad',
      attribute: '#fff5f6',
      definition: '#fdfdfd',
      keyword: '#f4eee4',
      operator: '#f4eee4',
      property: '#fdfdfd',
      number: '#f97e72',
      string: '#ff8b39',
      comment: '#6d77b3',
      meta: '#ff8b39',
      tag: '#f92aad',
    },
  },
  {
    id: 'twilight',
    name: 'Twilight',
    highlights: {
      background: '#141414',
      text: '#f7f7f7',
      variable: '#607392',
      attribute: '#d6bb6d',
      definition: '#607392',
      keyword: '#f9ee98',
      operator: '#cda869',
      property: '#fff',
      number: '#ca7841',
      string: '#8f9d6a',
      comment: '#777',
      meta: '#f7f7f7',
      tag: '#997643',
    },
  },

  {
    id: 'yeti',
    name: 'Yeti',
    light: true,
    highlights: {
      background: '#ECEAE8',
      text: '#d1c9c0',
      variable: '#55b5db',
      variable2: '#a074c4',
      variable3: '#96c0d8',
      attribute: '#9fb96e',
      definition: '#55b5db',
      keyword: '#9fb96e',
      operator: '#9fb96e',
      property: '#a074c4',
      number: '#a074c4',
      string: '#96c0d8',
      comment: '#d4c8be',
      meta: '#96c0d8',
      tag: '#96c0d8',
    },
  },
  {
    id: 'zenburn',
    name: 'Zenburn',
    highlights: {
      background: '#3f3f3f',
      text: '#dcdccc',
      variable: '#dfaf8f',
      variable3: '#dcdccc',
      attribute: '#dfaf8f',
      definition: '#dcdccc',
      keyword: '#f0dfaf',
      operator: '#f0efd0',
      property: '#dfaf8f',
      number: '#dcdccc',
      string: '#cc9393',
      comment: '#7f9f7f',
      meta: '#f0dfaf',
      tag: '#93e0e3',
    },
  },
]

export const THEMES_HASH = toHash(THEMES)
export const FONTS_HASH = toHash(FONTS)

export const LANGUAGES = [
  {
    name: 'Auto',
    mode: 'auto',
  },
  {
    name: 'Apache',
    mode: 'apache',
    mime: 'text/apache',
    custom: true,
    highlight: true,
  },
  {
    name: 'Bash',
    mode: 'shell',
    mime: 'application/x-sh',
    highlight: true,
  },
  {
    name: 'Plain Text',
    mode: 'text',
  },
  {
    name: 'C',
    mode: 'clike',
    mime: 'text/x-csrc',
    short: 'c',
  },
  {
    name: 'C++',
    mode: 'clike',
    mime: 'text/x-c++src',
    short: 'c-like',
    highlight: true,
  },
  {
    name: 'C#',
    mode: 'clike',
    mime: 'text/x-csharp',
    short: 'csharp',
    highlight: true,
  },
  {
    name: 'Clojure',
    mode: 'clojure',
    highlight: true,
  },
  {
    name: 'COBOL',
    mode: 'cobol',
  },
  {
    name: 'CoffeeScript',
    mode: 'coffeescript',
    highlight: true,
  },
  {
    name: 'Crystal',
    mode: 'crystal',
    highlight: true,
  },
  {
    name: 'CSS',
    mode: 'css',
    highlight: true,
  },
  {
    name: 'CQL',
    mode: 'sql',
    mime: 'text/x-cassandra',
    short: 'cassandra',
  },
  {
    name: 'D',
    mode: 'd',
    highlight: true,
  },
  {
    name: 'Dart',
    mode: 'dart',
    highlight: true,
  },
  {
    name: 'Diff',
    mode: 'diff',
    mime: 'text/x-diff',
    highlight: true,
  },
  {
    name: 'Django',
    mode: 'django',
    highlight: true,
  },
  {
    name: 'Docker',
    mode: 'dockerfile',
    highlight: true,
  },
  {
    name: 'Elixir',
    mode: 'elixir',
    custom: true,
    highlight: true,
  },
  {
    name: 'Elm',
    mode: 'elm',
    highlight: true,
  },
  {
    name: 'Erlang',
    mode: 'erlang',
    highlight: true,
  },
  {
    name: 'F#',
    mime: 'text/x-fsharp',
    mode: 'mllike',
    short: 'fsharp',
    highlight: true,
  },
  {
    name: 'Fortran',
    mode: 'fortran',
    highlight: true,
  },
  {
    name: 'Gherkin',
    mode: 'gherkin',
    highlight: true,
  },
  {
    name: 'GraphQL',
    mode: 'graphql',
    custom: true,
  },
  {
    name: 'Go',
    mode: 'go',
    mime: 'text/x-go',
    highlight: true,
  },
  {
    name: 'Groovy',
    mode: 'groovy',
    highlight: true,
  },
  {
    name: 'Handlebars',
    mode: 'handlebars',
    highlight: true,
  },
  {
    name: 'Haskell',
    mode: 'haskell',
    highlight: true,
  },
  {
    name: 'HTML/XML',
    mode: 'htmlmixed',
  },
  {
    name: 'Java',
    mode: 'clike',
    mime: 'text/x-java',
    short: 'java',
    highlight: true,
  },
  {
    name: 'JavaScript',
    mode: 'javascript',
    short: 'javascript',
    highlight: true,
  },
  {
    name: 'JSON',
    mode: 'javascript',
    mime: 'application/json',
    short: 'json',
    highlight: true,
  },
  {
    name: 'JSX',
    mode: 'jsx',
    short: 'jsx',
  },
  {
    name: 'Julia',
    mode: 'julia',
    highlight: true,
  },
  {
    name: 'Kotlin',
    mode: 'clike',
    mime: 'text/x-kotlin',
    short: 'kotlin',
    highlight: true,
  },
  {
    name: 'LaTeX',
    mode: 'stex',
    short: 'latex',
    highlight: true,
  },
  {
    name: 'Lisp',
    mode: 'commonlisp',
    short: 'lisp',
    highlight: true,
  },
  {
    name: 'Lua',
    mode: 'lua',
    highlight: true,
  },
  {
    name: 'Markdown',
    mode: 'markdown',
    highlight: true,
  },
  {
    name: 'Mathematica',
    mode: 'mathematica',
    highlight: true,
  },
  {
    name: 'MATLAB/Octave',
    mode: 'octave',
    mime: 'text/x-octave',
    short: 'matlab',
    highlight: true,
  },
  {
    name: 'MySQL',
    mode: 'sql',
    mime: 'text/x-mysql',
    short: 'mysql',
  },
  {
    name: 'N-Triples',
    mode: 'ntriples',
    mime: 'application/n-triples',
  },
  {
    name: 'NGINX',
    mode: 'nginx',
    highlight: true,
  },
  {
    name: 'Nim',
    mode: 'nim',
    custom: true,
    highlight: true,
  },
  {
    name: 'Objective C',
    mode: 'clike',
    mime: 'text/x-objectivec',
    short: 'objectivec',
    highlight: true,
  },
  {
    name: 'OCaml',
    mode: 'mllike',
    short: 'ocaml',
    highlight: true,
  },
  {
    name: 'Pascal',
    mode: 'pascal',
  },
  {
    name: 'Perl',
    mode: 'perl',
    highlight: true,
  },
  {
    name: 'PHP',
    mode: 'php',
    mime: 'text/x-php',
    short: 'php',
    highlight: true,
  },
  {
    name: 'PowerShell',
    mode: 'powershell',
    highlight: true,
  },
  {
    name: 'Protocol Buffer',
    mode: 'protobuf',
  },
  {
    name: 'Python',
    mode: 'python',
    highlight: true,
  },
  {
    name: 'R',
    mode: 'r',
    highlight: true,
  },
  {
    name: 'RISC-V',
    mode: 'riscv',
    custom: true,
  },
  {
    name: 'Ruby',
    mode: 'ruby',
    highlight: true,
  },
  {
    name: 'Rust',
    mode: 'rust',
    highlight: true,
  },
  {
    name: 'Sass',
    mode: 'sass',
  },
  {
    name: 'Scala',
    mode: 'clike',
    mime: 'text/x-scala',
    short: 'scala',
    highlight: true,
  },
  {
    name: 'Smalltalk',
    mode: 'smalltalk',
    highlight: true,
  },
  {
    name: 'Solidity',
    mode: 'solidity',
    custom: true,
  },
  {
    name: 'SPARQL',
    mode: 'sparql',
    mime: 'application/sparql-query',
  },
  {
    name: 'SQL',
    mode: 'sql',
    highlight: true,
  },
  {
    name: 'Stylus',
    mode: 'stylus',
    mime: 'stylus',
    highlight: true,
  },
  {
    name: 'Swift',
    mode: 'swift',
    highlight: true,
  },
  {
    name: 'TCL',
    mode: 'tcl',
    highlight: true,
  },
  {
    name: 'TOML',
    mode: 'toml',
  },
  {
    name: 'Turtle',
    mode: 'turtle',
    mime: 'text/turtle',
  },
  {
    name: 'TypeScript',
    mode: 'javascript',
    mime: 'application/typescript',
    short: 'typescript',
    highlight: true,
  },
  {
    name: 'TSX',
    mode: 'jsx',
    mime: 'text/typescript-jsx',
    short: 'tsx',
  },
  {
    name: 'Twig',
    mode: 'twig',
    mime: 'text/x-twig',
    highlight: true,
  },
  {
    name: 'VB.NET',
    mode: 'vb',
  },
  {
    name: 'Verilog',
    mode: 'verilog',
    highlight: true,
  },
  {
    name: 'VHDL',
    mode: 'vhdl',
    highlight: true,
  },
  {
    name: 'Vue',
    mode: 'vue',
  },
  {
    name: 'XQuery',
    mode: 'xquery',
    highlight: true,
  },
  {
    name: 'YAML',
    mode: 'yaml',
    highlight: true,
  },
]

export const EXPORT_SIZES = [
  { id: '1x', name: '1x', value: 1 },
  { id: '2x', name: '2x', value: 2 },
  { id: '4x', name: '4x', value: 4 },
]

export const EXPORT_SIZES_HASH = toHash(EXPORT_SIZES)

export const LANGUAGE_MIME_HASH = toHash(LANGUAGES, 'mime')
export const LANGUAGE_MODE_HASH = toHash(LANGUAGES, 'mode')
export const LANGUAGE_NAME_HASH = toHash(LANGUAGES, 'short')

export const DEFAULT_LANGUAGE = 'auto'
export const DEFAULT_THEME = THEMES_HASH['panda-Gradation']
export const DEFAULT_BG_COLOR = 'rgba(171, 184, 195, 1)'
export const DEFAULT_BACKGROUND_IMAGE_SOURCE = 'builtin:panda-bg-01'
export const DEFAULT_EXPORT_SIZE = EXPORT_SIZES_HASH['2x']
export const DEFAULT_FONT_FAMILY = 'Google Sans Code'

export const COLORS = {
  BLACK: 'var(--color-black)',
  PRIMARY: 'var(--brand-primary)',
  SECONDARY: 'var(--color-secondary)',
  GRAY: 'var(--color-gray)',
  DARK_GRAY: 'var(--color-dark-gray)',
  HOVER: 'var(--color-hover)',
  PURPLE: 'var(--brand-purple)',
  DARK_PURPLE: 'var(--brand-purple-muted)',
  RED: 'var(--status-danger)',
  BLUE: 'var(--status-info)',
  GREEN: 'var(--status-success)',
}

export const DEFAULT_CODE = `const pluckDeep = key => obj => key.split('.').reduce((item, key) => item[key], obj)

const compose = (...fns) => res => fns.reduce((accNum, next) => next(accNum), res)

const getQueryStringObject = query => {
  if (query.state) {
    return deserializeState(query.state)
  }

  const state = mapper.map(readMappings, query)

  Object.keys(state).forEach(key => {
    if (state[key] === '') state[key] = undefined
  })

  return state
}`

export const DEFAULT_SETTINGS = {
  paddingVertical: '56px',
  paddingHorizontal: '56px',
  backgroundImage: null,
  backgroundImageSource: DEFAULT_BACKGROUND_IMAGE_SOURCE,
  backgroundImageSelection: null,
  backgroundMode: 'image',
  backgroundColor: DEFAULT_BG_COLOR,
  backgroundGradient: null,
  backgroundGradientBlendMode: null,
  glassEffect: false,
  glassBlurRadius: '18px',
  dropShadow: true,
  dropShadowOffsetY: '20px',
  dropShadowBlurRadius: '68px',
  theme: DEFAULT_THEME.id,
  windowTheme: 'none',
  codeMirrorBorder: false,
  codeMirrorBorderColor: 'rgba(255,255,255,1)',
  codeMirrorBorderRadius: '5px',
  language: DEFAULT_LANGUAGE,
  fontFamily: DEFAULT_FONT_FAMILY,
  fontSize: '16px',
  lineHeight: '133%',
  windowControls: true,
  widthAdjustment: true,
  lineNumbers: false,
  firstLineNumber: 1,
  exportSize: '2x',
  watermark: false,
  watermarkMode: 'logo',
  watermarkOpacity: '1',
  watermarkScale: '1',
  watermarkOffsetX: '0px',
  watermarkOffsetY: '0px',
  watermarkText: 'Panda',
  watermarkFontFamily: DEFAULT_FONT_FAMILY,
  watermarkTextSize: '96px',
  watermarkTextKerning: true,
  watermarkStrokeColor: '',
  watermarkStrokeWidth: '0px',
  watermarkFillEnabled: true,
  watermarkFillColor: '',
  watermarkFontUrl: null,
  squaredImage: false,
  hiddenCharacters: false,
  name: '',
  width: 680,
}

export const DEFAULT_WIDTHS = {
  minWidth: 320,
  maxWidth: 1280,
}

export const DEFAULT_PRESETS = [
  {
    ...DEFAULT_SETTINGS,
    backgroundMode: 'color',
    backgroundColor: 'rgba(101,232,235,1)',
    backgroundGradient: 'linear-gradient(135deg, #96F8D6 0%, #44D8F8 100%)',
    backgroundGradientBlendMode: null,
    dropShadow: true,
    theme: 'Panda-Gradation',
    windowTheme: 'none',
    codeMirrorBorder: false,
    codeMirrorBorderRadius: '12px',
    windowControls: true,
    icon: getAssetUrl('static/presets/panda01.webp'),
    id: 'preset:panda01',
  },
  {
    ...DEFAULT_SETTINGS,
    backgroundMode: 'color',
    backgroundColor: 'rgba(135,192,254,1)',
    backgroundGradient: 'linear-gradient(135deg, #67A5FE 0%, #A0D2FE 100%)',
    backgroundGradientBlendMode: null,
    dropShadow: true,
    theme: 'Panda-Gradation',
    windowTheme: 'bw',
    codeMirrorBorder: true,
    codeMirrorBorderColor: 'rgba(246,238,220,0.92)',
    codeMirrorBorderRadius: '12px',
    windowControls: true,
    icon: getAssetUrl('static/presets/panda02.webp'),
    id: 'preset:panda02',
  },
  {
    ...DEFAULT_SETTINGS,
    backgroundMode: 'color',
    backgroundColor: 'rgba(207,177,217,1)',
    backgroundGradient: 'linear-gradient(180deg, #C1D3F8 0%, #DC8FBA 100%)',
    backgroundGradientBlendMode: null,
    dropShadow: true,
    theme: 'Panda-Gradation',
    windowTheme: 'boxy',
    codeMirrorBorder: false,
    codeMirrorBorderRadius: '12px',
    windowControls: true,
    icon: getAssetUrl('static/presets/panda03.webp'),
    id: 'preset:panda03',
  },
  {
    ...DEFAULT_SETTINGS,
    backgroundMode: 'color',
    backgroundColor: 'rgba(108,123,253,1)',
    backgroundGradient: 'linear-gradient(135deg, #2AC9FC 0%, #AD2CFE 100%)',
    backgroundGradientBlendMode: null,
    dropShadow: true,
    theme: 'vscode-Gradation',
    windowTheme: 'boxy',
    codeMirrorBorder: false,
    codeMirrorBorderRadius: '12px',
    windowControls: true,
    icon: getAssetUrl('static/presets/panda04.webp'),
    id: 'preset:panda04',
  },
  {
    ...DEFAULT_SETTINGS,
    backgroundMode: 'color',
    backgroundColor: 'rgba(254,93,111,1)',
    backgroundGradient: 'linear-gradient(180deg, #FEA593 0%, #FE154B 100%)',
    backgroundGradientBlendMode: null,
    dropShadow: true,
    theme: 'vscode',
    windowTheme: 'boxy',
    codeMirrorBorder: false,
    codeMirrorBorderRadius: '12px',
    windowControls: true,
    icon: getAssetUrl('static/presets/panda05.webp'),
    id: 'preset:panda05',
  },
  {
    ...DEFAULT_SETTINGS,
    backgroundMode: 'color',
    backgroundColor: 'rgba(157,176,232,1)',
    backgroundGradient: 'linear-gradient(135deg, #77E6D0 0%, #C1A7F5 45%, #7461F0 100%)',
    backgroundGradientBlendMode: null,
    dropShadow: true,
    theme: 'Panda-Gradation',
    windowTheme: 'none',
    codeMirrorBorder: false,
    codeMirrorBorderRadius: '12px',
    windowControls: true,
    icon: getAssetUrl('static/presets/panda06.webp'),
    id: 'preset:panda06',
  },
  {
    ...DEFAULT_SETTINGS,
    backgroundMode: 'color',
    backgroundColor: 'rgba(201,175,226,1)',
    backgroundGradient: 'linear-gradient(180deg, #F3C4D6 0%, #9E99ED 100%)',
    backgroundGradientBlendMode: null,
    dropShadow: true,
    theme: 'Panda-Gradation',
    windowTheme: 'none',
    codeMirrorBorder: false,
    codeMirrorBorderRadius: '12px',
    windowControls: true,
    icon: getAssetUrl('static/presets/panda07.webp'),
    id: 'preset:panda07',
  },
  {
    ...DEFAULT_SETTINGS,
    backgroundMode: 'color',
    backgroundColor: 'rgba(110,101,198,1)',
    backgroundGradient: 'linear-gradient(135deg, #677BE6 0%, #714EA6 100%)',
    backgroundGradientBlendMode: null,
    dropShadow: true,
    theme: 'vscode-Gradation',
    windowTheme: 'none',
    codeMirrorBorder: false,
    codeMirrorBorderRadius: '12px',
    windowControls: true,
    icon: getAssetUrl('static/presets/panda08.webp'),
    id: 'preset:panda08',
  },
]
